CREATE TABLE `unluckyhouse` (
	`id`	INTEGER,
	`age`	INTEGER,
	`age_unit`	CHAR(1) DEFAULT 'Y',
	`gender`	CHAR(1) DEFAULT 'F',
	`initative`	CHAR(1) DEFAULT 'S',
	`approach`	VARCHAR(20),
	`news`	TEXT,
	`area`	VARCHAR(10),
	`address`	VARCHAR(255),
	`datetime`	DATETIME,
	`state`	INTEGER DEFAULT 0,
	`lat`	REAL DEFAULT 25.0,
	`lng`	REAL DEFAULT 119.5,
	`vlat`	REAL DEFAULT 25.0,
	`vlng`	REAL DEFAULT 119.5,
	`vazu`	INTEGER DEFAULT 0,
	`mtime`	DATETIME DEFAULT (datetime('now','localtime')),
	PRIMARY KEY(id)
);